version: '3.8'
services:
  postgresql:
    container_name: postgresql
    image: postgres:14.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=book1@3$5^7
    ports:
      - 5432:5432
    volumes:
      - /data:/var/lib/postgresql/data
