version: '1'
services:
  db_postgres:
    container_name: 'db_novelldeas'
    image: 'postgres:14.5'
    restart: always
    env_file:
      - .env
    ports:
      - '5435:5432'
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data/
